// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAq29fIGtDNCuc802S_36w0XSukn_nQQcE',
    appId: '1:170703658630:android:c2e6d1797f1f3c42f0fb07',
    messagingSenderId: '170703658630',
    projectId: 'news-app-d4b80',
    storageBucket: 'news-app-d4b80.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2jG-ngTijtm_K5S_mRQIXGeKpsvdeZxI',
    appId: '1:170703658630:ios:567ed191386b8d4ff0fb07',
    messagingSenderId: '170703658630',
    projectId: 'news-app-d4b80',
    storageBucket: 'news-app-d4b80.firebasestorage.app',
    iosBundleId: 'com.example.newsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2jG-ngTijtm_K5S_mRQIXGeKpsvdeZxI',
    appId: '1:170703658630:ios:567ed191386b8d4ff0fb07',
    messagingSenderId: '170703658630',
    projectId: 'news-app-d4b80',
    storageBucket: 'news-app-d4b80.firebasestorage.app',
    iosBundleId: 'com.example.newsApp',
  );

}